export const MESSAGE = {
  VALIDATION_ERROR: 'Invalid data',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  EMAIL_NOT_FOUND: 'Email not found',
  EMAIL_REQUIRED: 'Email is required',
  PASSWORD_REQUIRED: 'Password is required',
  PASSWORD_LENGTH: 'Password must be at least 6 to 180 characters',
  USERNAME_REQUIRED: 'Username is required',
  USERNAME_LENGTH: 'Username must be at least 3 to 50 characters',
  COUNTRY_REQUIRED: 'Country/Region is required',
  ACCOUNT_NOT_FOUND: 'Account not found',
  ACCOUNT_CREATED_SUCCESSFULLY: 'Account created successfully',
  USER_NAME_ALREADY_EXISTS: 'Username already exists',
  USER_NAME_NOT_FOUND: 'Username not found',
  INVALID_EMAIL_OR_PASSWORD: 'Invalid email or password',
  SIGN_IN_SUCCESSFULLY: 'Sign in successfully',
  ACCESS_TOKEN_REQUIRED: 'Access token is required',
  ACCESS_TOKEN_NOT_FOUND: 'Access token not found',
  REFRESH_TOKEN_REQUIRED: 'Refresh token is required',
  REFRESH_TOKEN_NOT_FOUND: 'Refresh token not found',
  LOGOUT_SUCCESSFULLY: 'Logout successfully'
}
